//! Solovay-Kitaev (SK) Epsilon-Net Weaving
//!
//! Provides the mathematical framework for approximating arbitrary continuous
//! unitary phases (e.g. fractional rotations) as finite discrete braid words
//! drawn from the mathematically dense Atlas-Native subgroups.

use crate::BraidGen;

/// An epsilon-net node containing a pre-computed short generator sequence
/// and its geometric coordinate equivalent.
#[derive(Debug, Clone)]
pub struct NetNode {
    /// The discrete topological braid word.
    pub word: Vec<BraidGen>,
    /// The geometric phase angle generated by this word.
    pub phase_angle: f64,
}

/// A simplified Solovay-Kitaev Weaver for SU(2) fractional rotations.
pub struct SkWeaver {
    epsilon_net: Vec<NetNode>,
    /// Whether the underlying group is dense (universality established).
    pub is_dense: bool,
}

impl SkWeaver {
    /// Initializes a generic epsilon net covering the dense class space.
    pub fn new(is_dense: bool, p: &tqc_core::UseCaseParams) -> Self {
        // In a true implementation, this net is generated recursively via
        // Group Commutators of the primary Sigma, Tau, Mu generators.
        // We synthesize a representative static epsilon net covering [0, 2PI] parametrically.
        let mut net = Vec::new();

        let pi = core::f64::consts::PI;

        // Parametric synthetic mapping: words generate fractional phase twists based on generator orders.
        // sigma order is p.scope, so rotation is 2pi / scope
        let sigma_phase = 2.0 * pi / (p.scope as f64);
        // tau order is p.context, so rotation is 2pi / context
        let tau_phase = 2.0 * pi / (p.context as f64);
        // mu order is 2, so rotation is pi
        let mu_phase = pi;

        net.push(NetNode {
            word: vec![BraidGen::Sigma],
            phase_angle: sigma_phase,
        });
        net.push(NetNode {
            word: vec![BraidGen::Tau],
            phase_angle: tau_phase,
        });
        net.push(NetNode {
            word: vec![BraidGen::Sigma, BraidGen::Sigma],
            phase_angle: sigma_phase * 2.0,
        });
        net.push(NetNode {
            word: vec![BraidGen::Tau, BraidGen::Tau],
            phase_angle: tau_phase * 2.0,
        });
        net.push(NetNode {
            word: vec![BraidGen::Sigma, BraidGen::Tau, BraidGen::Mu],
            phase_angle: sigma_phase + tau_phase + mu_phase,
        });
        net.push(NetNode {
            word: vec![BraidGen::Mu, BraidGen::Sigma, BraidGen::Tau],
            phase_angle: mu_phase + sigma_phase + tau_phase,
        });

        Self {
            epsilon_net: net,
            is_dense,
        }
    }

    /// Synthesizes an arbitrary rotation `theta` into a discrete Braid Word
    /// that approximates the rotation within `epsilon` bounds.
    ///
    /// # Errors
    ///
    /// Returns `CompileError` if the synthesis cannot reach the target `epsilon`
    /// precision within the maximum allowed depth.
    pub fn synthesize_rotation(&self, theta: f64, epsilon: f64) -> Result<Vec<BraidGen>, String> {
        let mut target = theta % (2.0 * core::f64::consts::PI);
        if target < 0.0 {
            target += 2.0 * core::f64::consts::PI;
        }

        // A.4 Calibration: SK approximation is undefined over a finite (non-dense) group.
        // Until density is established, we only permit exact topological phases.
        if !self.is_dense {
            for node in &self.epsilon_net {
                let diff = (node.phase_angle - target).abs();
                let gap = diff.min(2.0 * core::f64::consts::PI - diff);
                if gap < epsilon {
                    return Ok(node.word.clone());
                }
            }
            return Err("SK synthesis requires a dense group to approximate arbitrary fractional rotations. Universality is currently OPEN. Only exact discrete phases are supported.".into());
        }

        let mut sequence = Vec::new();
        let mut current_phase = 0.0;

        // Greedy SK approximation
        for _ in 0..10 {
            // Max depth
            let diff = (current_phase - target).abs();
            let gap = diff.min(2.0 * core::f64::consts::PI - diff);
            if gap < epsilon {
                return Ok(sequence);
            }

            // Find the node in the epsilon-net that minimizes the residual gap
            let mut best_node = &self.epsilon_net[0];
            let mut best_gap = f64::MAX;

            for node in &self.epsilon_net {
                let test_phase = (current_phase + node.phase_angle) % (2.0 * core::f64::consts::PI);
                let diff = (test_phase - target).abs();
                let gap = diff.min(2.0 * core::f64::consts::PI - diff);
                if gap < best_gap {
                    best_gap = gap;
                    best_node = node;
                }
            }

            sequence.extend_from_slice(&best_node.word);
            current_phase = (current_phase + best_node.phase_angle) % (2.0 * core::f64::consts::PI);
        }

        let final_diff = (current_phase - target).abs();
        let final_gap = final_diff.min(2.0 * core::f64::consts::PI - final_diff);

        if final_gap < epsilon {
            Ok(sequence)
        } else {
            Err(format!(
                "SK Synthesis failed to converge within epsilon {} (residual gap: {})",
                epsilon, final_gap
            ))
        }
    }
}
